### ISSUE TITLE
Medium post/tutorial

### ISSUE THREAD

**Issue by ToJen** [jstoxrocky/0x2048-frontend#34]
Interesting project with state channels. Will you make a tutorial on this and the accompanying repos? I made a [2048 player](https://github.com/ToJen/Solve-2048.git) a while ago with Selenium if you want to test stuff out.

**Comment by jstoxrocky** [comment]
@ToJen Thanks, I definitely will write something up soon. After completing an initial version of this idea, I realized a lot of the logic involved in making this decentralized also made it confusing from a UX perspective. So I had a good think on that and am using some new ideas to make V2 both decentralized and user friendly. I will write something up about the differences/pros/cons between V1 and V2 when I get V2 working. Thanks for your interest! (haha gabrielecirulli's version of 2048 is wayyyyyyyyy more polished than mine)

**Comment by ToJen** [comment]
Cool, good luck man!
